org: javier0rosas
app: nebulaii-backend
service: nebulaii-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors: true
  logs:
    httpApi: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: "arn:aws:s3:::nebulaii-test/*"

package:
  individually: true

functions:
  auth:
    handler: src/auth/handler.handler
  upload:
    handler: src/upload/handler.handler
    events:
      - httpApi: 
          path: /upload
          method: get
  embedding:
    handler: src/embedding/handler.handler
    events:
      - httpApi: 
          path: /embedding
          method: get
  search:
    handler: src/search/handler.handler
  payments:
    handler: src/payments/handler.handler

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
